{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8ac03df6",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.datasets import load_iris, load_breast_cancer\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import accuracy_score\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "# -------------------- UI --------------------\n",
    "st.set_page_config(page_title=\"ML Playground\", layout=\"wide\")\n",
    "st.title(\"🧠 Interactive Machine Learning Playground\")\n",
    "st.write(\"Experiment with datasets, models, and hyperparameters in real time.\")\n",
    "\n",
    "# -------------------- Sidebar --------------------\n",
    "st.sidebar.header(\"⚙️ Configuration\")\n",
    "\n",
    "dataset_name = st.sidebar.selectbox(\n",
    "    \"Select Dataset\",\n",
    "    (\"Iris\", \"Breast Cancer\")\n",
    ")\n",
    "\n",
    "model_name = st.sidebar.selectbox(\n",
    "    \"Select Model\",\n",
    "    (\"Logistic Regression\", \"Random Forest\", \"SVM\")\n",
    ")\n",
    "\n",
    "test_size = st.sidebar.slider(\"Test Size\", 0.1, 0.5, 0.2)\n",
    "\n",
    "# -------------------- Load Dataset --------------------\n",
    "def load_dataset(name):\n",
    "    if name == \"Iris\":\n",
    "        data = load_iris()\n",
    "    else:\n",
    "        data = load_breast_cancer()\n",
    "    X = pd.DataFrame(data.data, columns=data.feature_names)\n",
    "    y = pd.Series(data.target)\n",
    "    return X, y\n",
    "\n",
    "X, y = load_dataset(dataset_name)\n",
    "\n",
    "st.subheader(\"📊 Dataset Preview\")\n",
    "st.dataframe(X.head())\n",
    "\n",
    "# -------------------- Visualization --------------------\n",
    "st.subheader(\"📈 Feature Visualization\")\n",
    "feature_x = st.selectbox(\"X-axis Feature\", X.columns)\n",
    "feature_y = st.selectbox(\"Y-axis Feature\", X.columns)\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "sns.scatterplot(\n",
    "    x=X[feature_x],\n",
    "    y=X[feature_y],\n",
    "    hue=y,\n",
    "    palette=\"deep\",\n",
    "    ax=ax\n",
    ")\n",
    "ax.set_title(\"Feature Relationship\")\n",
    "st.pyplot(fig)\n",
    "\n",
    "# -------------------- Train/Test Split --------------------\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=test_size, random_state=42\n",
    ")\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "# -------------------- Model Selection --------------------\n",
    "def get_model(name):\n",
    "    if name == \"Logistic Regression\":\n",
    "        C = st.sidebar.slider(\"Regularization (C)\", 0.01, 10.0, 1.0)\n",
    "        model = LogisticRegression(C=C, max_iter=1000)\n",
    "\n",
    "    elif name == \"Random Forest\":\n",
    "        n_estimators = st.sidebar.slider(\"Number of Trees\", 50, 300, 100)\n",
    "        max_depth = st.sidebar.slider(\"Max Depth\", 2, 20, 5)\n",
    "        model = RandomForestClassifier(\n",
    "            n_estimators=n_estimators,\n",
    "            max_depth=max_depth,\n",
    "            random_state=42\n",
    "        )\n",
    "\n",
    "    else:\n",
    "        C = st.sidebar.slider(\"C\", 0.1, 10.0, 1.0)\n",
    "        kernel = st.sidebar.selectbox(\"Kernel\", (\"linear\", \"rbf\"))\n",
    "        model = SVC(C=C, kernel=kernel)\n",
    "\n",
    "    return model\n",
    "\n",
    "model = get_model(model_name)\n",
    "\n",
    "# -------------------- Training --------------------\n",
    "model.fit(X_train, y_train)\n",
    "preds = model.predict(X_test)\n",
    "accuracy = accuracy_score(y_test, preds)\n",
    "\n",
    "# -------------------- Results --------------------\n",
    "st.subheader(\"✅ Model Performance\")\n",
    "st.metric(\"Accuracy\", f\"{accuracy * 100:.2f}%\")\n",
    "\n",
    "st.success(\"Model trained successfully!\")\n",
    "\n",
    "# -------------------- Footer --------------------\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"🚀 Built for learning & experimentation | Classic Machine Learning\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95232c08",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
